name: cargo-release-validator
description: Makes sure a Rust project's Cargo File contains a valid semantic version that makes sense.

branding:
  icon: check-circle
  color: red

inputs:
  cargoManifest:
    description: The Cargo Manifest File to validate.
    required: false
    default: Cargo.toml
  prefix:
    description: An optional prefix that tags must start with.
    required: false

runs:
  using: node16
  main: dist/index.js
