name: Publish

on:
  release:
    types:
      - published
      - edited

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
          
      - name: Setup Node
        uses: actions/setup-node@v2
      
      - name: Install Dependencies
        run: npm ci

      - name: Build Action
        run: npm run build

      - uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
